export interface ControlDefinition {
  key: string
  label: string
  type: 'slider' | 'color' | 'toggle' | 'select' | 'text'
  min?: number
  max?: number
  step?: number
  options?: { label: string; value: string }[]
}

export interface BackgroundPreset {
  id: string
  componentName: string
  name: string
  description: string
  controls: ControlDefinition[]
  defaultConfig: Record<string, any>
}

export const presetCatalog: BackgroundPreset[] = [
  {
    id: 'dotfield',
    componentName: 'DotField',
    name: 'Interactive Dot Field',
    description: 'A grid of depth-mapped dots that react to mouse movements, custom clicks, and automatic pulses.',
    defaultConfig: {
      spacing: 28,
      dotSize: 1.5,
      intensity: 1.2,
      pulseEvery: 2800,
      autoPulse: true,
      dotColor: '#0ea5e9',
      accentColor: '#f59e0b',
      interaction: 'repel',
    },
    controls: [
      { key: 'spacing', label: 'Grid Spacing', type: 'slider', min: 15, max: 60, step: 1 },
      { key: 'dotSize', label: 'Dot Base Size', type: 'slider', min: 0.5, max: 4.0, step: 0.1 },
      { key: 'intensity', label: 'Ripple Force', type: 'slider', min: 0.1, max: 3.0, step: 0.1 },
      { key: 'pulseEvery', label: 'Pulse Interval (ms)', type: 'slider', min: 1000, max: 8000, step: 100 },
      { key: 'autoPulse', label: 'Auto Pulse Wave', type: 'toggle' },
      { key: 'dotColor', label: 'Dot Color', type: 'color' },
      { key: 'accentColor', label: 'Ripple Wave Color', type: 'color' },
      {
        key: 'interaction',
        label: 'Pointer Interaction',
        type: 'select',
        options: [
          { label: 'Repel Dots', value: 'repel' },
          { label: 'Attract Dots', value: 'attract' },
          { label: 'None', value: 'none' },
        ],
      },
    ],
  },
  {
    id: 'constellation',
    componentName: 'Constellation',
    name: 'Dynamic Constellation',
    description: 'Floating nodes moving through 2D space, forming lines to adjacent nodes when they drift close.',
    defaultConfig: {
      particleCount: 80,
      particleSize: 2.0,
      linkDistance: 120,
      speed: 1.0,
      color: '#a855f7',
      lineOpacity: 0.25,
      interactive: true,
    },
    controls: [
      { key: 'particleCount', label: 'Particle Count', type: 'slider', min: 20, max: 200, step: 5 },
      { key: 'particleSize', label: 'Particle Size', type: 'slider', min: 0.5, max: 5.0, step: 0.1 },
      { key: 'linkDistance', label: 'Link Distance', type: 'slider', min: 50, max: 250, step: 5 },
      { key: 'speed', label: 'Movement Speed', type: 'slider', min: 0.1, max: 4.0, step: 0.1 },
      { key: 'color', label: 'Constellation Color', type: 'color' },
      { key: 'lineOpacity', label: 'Line Opacity', type: 'slider', min: 0.05, max: 0.9, step: 0.05 },
      { key: 'interactive', label: 'Attract to Pointer', type: 'toggle' },
    ],
  },
  {
    id: 'flowfield',
    componentName: 'FlowField',
    name: 'Perlin Flow Field',
    description: 'Drifting paint-like trails tracing vectors through a continuous Simplex/Perlin noise field.',
    defaultConfig: {
      particleCount: 300,
      speed: 1.5,
      noiseScale: 0.005,
      trailFade: 0.08,
      lineWidth: 1.2,
      primaryColor: '#6366f1',
      secondaryColor: '#ec4899',
    },
    controls: [
      { key: 'particleCount', label: 'Simultaneous Streams', type: 'slider', min: 100, max: 800, step: 20 },
      { key: 'speed', label: 'Stream Speed', type: 'slider', min: 0.5, max: 5.0, step: 0.1 },
      { key: 'noiseScale', label: 'Flow Complexity', type: 'slider', min: 0.001, max: 0.02, step: 0.001 },
      { key: 'trailFade', label: 'Trail Persistence', type: 'slider', min: 0.01, max: 0.3, step: 0.01 },
      { key: 'lineWidth', label: 'Stream Width', type: 'slider', min: 0.5, max: 4.0, step: 0.1 },
      { key: 'primaryColor', label: 'Primary Gradient', type: 'color' },
      { key: 'secondaryColor', label: 'Secondary Gradient', type: 'color' },
    ],
  },
  {
    id: 'aurora',
    componentName: 'Aurora',
    name: 'CSS Aurora Glass',
    description: 'Extremely lightweight, highly blurred moving fluid gradients styled entirely with CSS variables.',
    defaultConfig: {
      blobCount: 4,
      blur: 80,
      speed: 20,
      opacity: 0.5,
      color1: '#a855f7',
      color2: '#0ea5e9',
      color3: '#10b981',
      color4: '#f43f5e',
    },
    controls: [
      { key: 'blobCount', label: 'Fluid Blobs', type: 'slider', min: 2, max: 6, step: 1 },
      { key: 'blur', label: 'Blur Intensity (px)', type: 'slider', min: 40, max: 150, step: 5 },
      { key: 'speed', label: 'Flow Duration (s)', type: 'slider', min: 5, max: 60, step: 1 },
      { key: 'opacity', label: 'Overall Opacity', type: 'slider', min: 0.1, max: 1.0, step: 0.05 },
      { key: 'color1', label: 'Blob 1 Color', type: 'color' },
      { key: 'color2', label: 'Blob 2 Color', type: 'color' },
      { key: 'color3', label: 'Blob 3 Color', type: 'color' },
      { key: 'color4', label: 'Blob 4 Color', type: 'color' },
    ],
  },
  {
    id: 'jellyfish',
    componentName: 'Jellyfish',
    name: 'Wave Ribbons (Jellyfish)',
    description: 'Sinuous waves of bezier ribbons flowing horizontally across the canvas, bending dynamically near the cursor.',
    defaultConfig: {
      waveCount: 6,
      lineThickness: 2.0,
      speed: 1.2,
      frequency: 0.003,
      amplitude: 45,
      color: '#60a5fa',
      opacity: 0.35,
      interactive: true,
    },
    controls: [
      { key: 'waveCount', label: 'Ribbon Count', type: 'slider', min: 2, max: 12, step: 1 },
      { key: 'lineThickness', label: 'Line Thickness', type: 'slider', min: 0.5, max: 6.0, step: 0.5 },
      { key: 'speed', label: 'Wave Speed', type: 'slider', min: 0.1, max: 4.0, step: 0.1 },
      { key: 'frequency', label: 'Wave Frequency', type: 'slider', min: 0.001, max: 0.01, step: 0.0005 },
      { key: 'amplitude', label: 'Wave Amplitude', type: 'slider', min: 10, max: 120, step: 5 },
      { key: 'color', label: 'Ribbon Color', type: 'color' },
      { key: 'opacity', label: 'Base Opacity', type: 'slider', min: 0.1, max: 1.0, step: 0.05 },
      { key: 'interactive', label: 'Hover Interactive', type: 'toggle' },
    ],
  },
  {
    id: 'matrix',
    componentName: 'MatrixRain',
    name: 'Terminal Matrix Rain',
    description: 'Vertically dripping binary/custom character columns fading in real-time, slowing under pointer heat.',
    defaultConfig: {
      speed: 1.2,
      fontSize: 14,
      trailFade: 0.06,
      color: '#10b981',
      customText: 'DECH01',
      density: 0.85,
      interactive: true,
    },
    controls: [
      { key: 'speed', label: 'Falling Speed', type: 'slider', min: 0.2, max: 3.0, step: 0.1 },
      { key: 'fontSize', label: 'Font size (px)', type: 'slider', min: 8, max: 32, step: 1 },
      { key: 'trailFade', label: 'Drip Fade Speed', type: 'slider', min: 0.01, max: 0.2, step: 0.01 },
      { key: 'color', label: 'Text Color', type: 'color' },
      { key: 'customText', label: 'Custom Characters', type: 'text' },
      { key: 'density', label: 'Column Density', type: 'slider', min: 0.1, max: 0.95, step: 0.05 },
      { key: 'interactive', label: 'Friction Under Pointer', type: 'toggle' },
    ],
  },
  {
    id: 'nebula',
    componentName: 'Nebula',
    name: 'Cosmic Nebula Orbit',
    description: 'Orbiting stars rotating around a gravitational center that smoothly shifts and tracks the mouse cursor.',
    defaultConfig: {
      starCount: 140,
      orbitRadius: 180,
      rotateSpeed: 1.2,
      starSize: 1.8,
      starColor: '#f472b6',
      coreColor: '#38bdf8',
      tailLength: 0.08,
    },
    controls: [
      { key: 'starCount', label: 'Star Count', type: 'slider', min: 50, max: 300, step: 10 },
      { key: 'orbitRadius', label: 'Galaxy Size', type: 'slider', min: 50, max: 350, step: 10 },
      { key: 'rotateSpeed', label: 'Orbit Velocity', type: 'slider', min: 0.1, max: 4.0, step: 0.1 },
      { key: 'starSize', label: 'Star Size', type: 'slider', min: 0.5, max: 5.0, step: 0.1 },
      { key: 'starColor', label: 'Star Color', type: 'color' },
      { key: 'coreColor', label: 'Core Glow Color', type: 'color' },
      { key: 'tailLength', label: 'Space Friction (Fade)', type: 'slider', min: 0.01, max: 0.3, step: 0.01 },
    ],
  },
  {
    id: 'hexgrid',
    componentName: 'HexGrid',
    name: 'Glow Honeycomb',
    description: 'A mathematical honeycomb grid that radiates colorful light waves outwards from click points.',
    defaultConfig: {
      cellSize: 32,
      gapSize: 3.0,
      rippleSpeed: 0.35,
      color: '#f59e0b',
      bgColor: '#27272a',
      opacity: 0.20,
      interactive: true,
    },
    controls: [
      { key: 'cellSize', label: 'Honeycomb Size', type: 'slider', min: 12, max: 80, step: 2 },
      { key: 'gapSize', label: 'Cell Gap Width', type: 'slider', min: 0, max: 10, step: 0.5 },
      { key: 'rippleSpeed', label: 'Wave Ripple Velocity', type: 'slider', min: 0.1, max: 1.2, step: 0.05 },
      { key: 'color', label: 'Glow Wave Color', type: 'color' },
      { key: 'bgColor', label: 'Base Cell Color', type: 'color' },
      { key: 'opacity', label: 'Grid Opacity', type: 'slider', min: 0.05, max: 0.8, step: 0.05 },
      { key: 'interactive', label: 'Hover Glow Active', type: 'toggle' },
    ],
  },
  {
    id: 'fireflies',
    componentName: 'Fireflies',
    name: 'Mystical Fireflies',
    description: 'Glowing fireflies floating around with smooth random walks, light trails, and cursor interaction.',
    defaultConfig: {
      particleCount: 60,
      particleSize: 3.0,
      glowRadius: 8,
      speed: 1.0,
      color: '#eab308',
      trailLength: 0.15,
      interactive: true,
    },
    controls: [
      { key: 'particleCount', label: 'Firefly Count', type: 'slider', min: 10, max: 150, step: 5 },
      { key: 'particleSize', label: 'Body Size', type: 'slider', min: 1.0, max: 6.0, step: 0.5 },
      { key: 'glowRadius', label: 'Glow Radius', type: 'slider', min: 2, max: 20, step: 1 },
      { key: 'speed', label: 'Movement Speed', type: 'slider', min: 0.1, max: 4.0, step: 0.1 },
      { key: 'color', label: 'Glow Color', type: 'color' },
      { key: 'trailLength', label: 'Trail Opacity (Fade)', type: 'slider', min: 0.05, max: 0.5, step: 0.05 },
      { key: 'interactive', label: 'Attract to Pointer', type: 'toggle' },
    ],
  },
  {
    id: 'synthwave',
    componentName: 'Synthwave',
    name: 'Retro Synthwave Grid',
    description: 'A 3D perspective wireframe grid moving towards the viewer beneath a glowing neon sun.',
    defaultConfig: {
      gridSpeed: 2.0,
      gridColor: '#ec4899',
      sunColor: '#f59e0b',
      sunSize: 120,
      sunY: 120,
      perspective: 300,
      fogDensity: 0.4,
    },
    controls: [
      { key: 'gridSpeed', label: 'Scroll Velocity', type: 'slider', min: 0.5, max: 5.0, step: 0.1 },
      { key: 'gridColor', label: 'Grid Wireframe Color', type: 'color' },
      { key: 'sunColor', label: 'Sunset Sun Color', type: 'color' },
      { key: 'sunSize', label: 'Sun Radius (px)', type: 'slider', min: 50, max: 200, step: 5 },
      { key: 'sunY', label: 'Sun Vertical Offset', type: 'slider', min: -50, max: 250, step: 5 },
      { key: 'perspective', label: '3D Projection Depth', type: 'slider', min: 100, max: 600, step: 10 },
      { key: 'fogDensity', label: 'Horizon Glow (Fog)', type: 'slider', min: 0.1, max: 0.9, step: 0.05 },
    ],
  },
  {
    id: 'voronoi',
    componentName: 'Voronoi',
    name: 'Dynamic Voronoi Cells',
    description: 'Morphing cell structures based on moving distance vectors, drawing custom borders over gradients.',
    defaultConfig: {
      cellCount: 35,
      lineWidth: 1.5,
      speed: 0.8,
      lineColor: '#3b82f6',
      bgGradient1: '#0f172a',
      bgGradient2: '#1e1b4b',
      interactive: true,
    },
    controls: [
      { key: 'cellCount', label: 'Cell Count', type: 'slider', min: 10, max: 80, step: 5 },
      { key: 'lineWidth', label: 'Border Width', type: 'slider', min: 0.5, max: 5.0, step: 0.5 },
      { key: 'speed', label: 'Morphing Velocity', type: 'slider', min: 0.1, max: 3.0, step: 0.1 },
      { key: 'lineColor', label: 'Cell Border Color', type: 'color' },
      { key: 'bgGradient1', label: 'BG Gradient Start', type: 'color' },
      { key: 'bgGradient2', label: 'BG Gradient End', type: 'color' },
      { key: 'interactive', label: 'Hover Interactive', type: 'toggle' },
    ],
  },
]
